### ISSUE TITLE
打包后访问页面时报错

### ISSUE THREAD

**Issue by fatfatcat** [pengqiangsheng/vue-magic-tree#3]
`vendor1.7d71db32.dll.js:7 TypeError: Cannot read property 'init' of undefined
    at a.<anonymous> (ztree.vue:104)`

涉及到的代码是下面这段的
`this.$nextTick(() => {
          this.ztreeObj = $.fn.zTree.init($("#"+this.ztreeId), Object.assign({}, this.ztreeSetting, this.setting), this.list);
          this.$emit('onCreated', this.ztreeObj)
        })`

**Comment by pengqiangsheng** [comment]
> `vendor1.7d71db32.dll.js:7 TypeError: Cannot read property 'init' of undefined at a.<anonymous> (ztree.vue:104)`
> 
> 涉及到的代码是下面这段的
> `this.$nextTick(() => { this.ztreeObj = $.fn.zTree.init($("#"+this.ztreeId), Object.assign({}, this.ztreeSetting, this.setting), this.list); this.$emit('onCreated', this.ztreeObj) })`

说明 $.fn.zTree是null，也就是说你可能没有jQuery，$就不起作用了，自然没有后面的。需要进一步排查。

**Comment by fatfatcat** [comment]
开发环境运行没有问题的，只有打包后部署到Nginx下会报这个错，不知道为啥。。
我看源码中开头有`import $ from 'jquery'
if (!window.jQuery) {
  window.jQuery = $
}`
是不是意味着如果没有jQuery，import时就会报错了？

**Comment by pengqiangsheng** [comment]
你应该要看下webpack怎么配置jquery。

**Comment by fatfatcat** [comment]
解决了，项目里创建了jquery的包装对象jquery-vendor.js，在用到vue-magic-tree的组件里重新import一下就可以了
import $ from '../../common/directives/jquery-vendor'
import VueMagicTree from 'vue-magic-tree'
